Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |vb|
   vb.customize ["modifyvm", :id, "--memory", "1024"]
   vb.name = "rancher-srv"
 end
 config.vm.box = "centos/7"
 config.vm.hostname = "rancher-srv"
 config.vm.network "private_network", ip: "192.168.50.50"
 config.vm.provision :shell, path: "../server.sh"
 config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/London /etc/localtime", run: "always"
end
